apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: rc-local-pv
    namespace: ""
    resourceVersion: "1565"
    selfLink: /api/v1/persistentvolumes/rc-local-pv
    uid: 1106cb9b-ba9f-11e8-af74-005056871190
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: misty-narwhal-pv-claim
    local:
      path: /apic
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - px-chrisp1
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
